# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]
handlers:
- url: /(.*\.(gif|png|jpg|css|mp4|svg|ogg|mp3|js|json)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
skip_files:
- ^(?!dist)  # Skip any files not in the dist folder